name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs every 6 hours
    - cron: "0 */6 * * *" 

jobs:
  update-readme:
    name: Waka Metrics
    runs-on: ubuntu-latest
    steps:
       - uses: athul/waka-readme@master # do NOT replace with anything else
         with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} 
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
